package co.gov.supernotariado.bachue.correspondencia.ws.enviofisico;

import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;

import co.gov.supernotariado.bachue.correspondencia.ejb.negocio.ParametrosStatelessLocal;
import co.gov.supernotariado.bachue.correspondencia.ejb.negocio.ProcesosStatelessLocal;
import https.www_supernotariado_gov_co.schemas.bachue.cr.enviocorrespondenciafisica.enviarcorrespondenciafisica.v1.TipoEntradaEnviarCorrespondenciaFisica;
import https.www_supernotariado_gov_co.schemas.bachue.cr.enviocorrespondenciafisica.enviarcorrespondenciafisica.v1.TipoSalidaEnviarCorrespondenciaFisica;
import https.www_supernotariado_gov_co.services.bachue.cr.enviocorrespondenciafisica.v1.SUTCREnvioCorrespondenciaFisica;

/**
 * Clase de entrada para el servicio expuesto SUT_CR_EnvioCorrespondenciaFisica
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "SUT_CR_EnvioCorrespondenciaFisicaPort", serviceName = "SUT_CR_EnvioCorrespondenciaFisica", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cr/enviocorrespondenciafisica/v1", wsdlLocation = "/wsdls/BS_SUT_CR_EnvioCorrespondenciaFisica.wsdl", endpointInterface = "https.www_supernotariado_gov_co.services.bachue.cr.enviocorrespondenciafisica.v1.SUTCREnvioCorrespondenciaFisica")
@BindingType("http://www.w3.org/2003/05/soap/bindings/HTTP/")
public class SUT_CR_EnvioCorrespondenciaFisica_SUT_CR_EnvioCorrespondenciaFisicaPortImpl
    implements SUTCREnvioCorrespondenciaFisica
{

	/**
	 * Contexto del servicio web
	 */
	@Resource
	private WebServiceContext wsContext;

	/** Manejador de lógica de negocio de procesos */
	@EJB(name = "ProcesoBusiness")
	private ProcesosStatelessLocal procesoControl;

	/** Manejador de lógica de negocio de parámetros */
	@EJB(name = "ParametrosBusiness")
	private ParametrosStatelessLocal parametrosControl;

    /**
     * Invoca al Método principal del servicio, realiza el cambio de etapa de un proceso para avanzarlo a la etapa de Envío
     * @param entrada Parámetros de entrada del servicio web
     * @return Respuesta del servicio web con el un código de salida y un mensaje
     */
    public TipoSalidaEnviarCorrespondenciaFisica enviarCorrespondenciaFisica(TipoEntradaEnviarCorrespondenciaFisica entrada) {
        //replace with your impl here
    	EnvioCorrespondenciaFisica servicio = new EnvioCorrespondenciaFisica();
    	servicio.setProcesoControl(procesoControl);
    	servicio.setParametrosControl(parametrosControl);
    	return servicio.enviarCorrespondenciaFisica(entrada, wsContext);
    }

}
