package co.gov.supernotariado.bachue.correspondencia.ws.generacionee;

import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;

import co.gov.supernotariado.bachue.correspondencia.ejb.negocio.ParametrosStatelessLocal;
import co.gov.supernotariado.bachue.correspondencia.ejb.negocio.ProcesosStatelessLocal;
import co.gov.supernotariado.bachue.correspondencia.ejb.negocio.SecuenciasSingletonLocal;
import https.www_supernotariado_gov_co.schemas.bachue.cr.generacionidscorrespondencia.obtenereecorrespondencia.v1.TipoEntradaObtenerEECorrespondencia;
import https.www_supernotariado_gov_co.schemas.bachue.cr.generacionidscorrespondencia.obtenereecorrespondencia.v1.TipoSalidaObtenerEECorrespondencia;
import https.www_supernotariado_gov_co.services.bachue.cr.generacionidscorrespondencia.v1.SUTCRGeneracionIDsCorrespondencia;


/**
 * Clase de entrada para el servicio expuesto SUT_CR_GeneracionIDsCorrespondencia
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "SUT_CR_GeneracionIDsCorrespondenciaPort", serviceName = "SUT_CR_GeneracionIDsCorrespondencia", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cr/generacionidscorrespondencia/v1", wsdlLocation = "/wsdls/BS_SUT_CR_GeneracionIDsCorrespondencia.wsdl", endpointInterface = "https.www_supernotariado_gov_co.services.bachue.cr.generacionidscorrespondencia.v1.SUTCRGeneracionIDsCorrespondencia")
@BindingType("http://www.w3.org/2003/05/soap/bindings/HTTP/")
public class SUT_CR_GeneracionIDsCorrespondencia_SUT_CR_GeneracionIDsCorrespondenciaPortImpl
    implements SUTCRGeneracionIDsCorrespondencia
{

	/**
	 * Contexto del servicio web
	 */
	@Resource
	private WebServiceContext wsContext;

	/** Manejador de lógica de negocio de procesos */
	@EJB(name = "ProcesoBusiness")
	private ProcesosStatelessLocal procesoControl;

	/** Manejador de lógica de negocio de secuencias */
	@EJB(name = "SecuenciasBusiness")
	private SecuenciasSingletonLocal secuenciasControl;

	/** Manejador de lógica de negocio de parámetros */
	@EJB(name = "ParametrosBusiness")
	private ParametrosStatelessLocal parametrosControl;

    /**
     * Invoca al Método principal del servicio, inicializa el proceso con los parámetros de entrada recibidos
     * @param entrada Parámetros de entrada del servicio web
     * @return Respuesta del servicio web con el un código de salida, un mensaje y un consecutivo EE
     */
    public TipoSalidaObtenerEECorrespondencia obtenerEECorrespondencia(TipoEntradaObtenerEECorrespondencia entrada) {
        //replace with your impl here
    	GeneracionEECorrespondencia servicio = new GeneracionEECorrespondencia();
    	servicio.setProcesoControl(procesoControl);
    	servicio.setSecuenciasControl(secuenciasControl);
    	servicio.setParametrosControl(parametrosControl);
    	return servicio.obtenerEECorrespondencia(entrada, wsContext);
    }

}
