
package co.gov.supernotariado.bachue.correspondencia.ws.notificardigitalizacion;

import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;

import co.gov.supernotariado.bachue.correspondencia.ejb.negocio.ParametrosStatelessLocal;
import co.gov.supernotariado.bachue.correspondencia.ejb.negocio.ProcesosStatelessLocal;
import https.www_supernotariado_gov_co.schemas.bachue.cr.controldigitalizacion.notificardigitalizacion.v1.TipoEntradaNotificarDigitalizacion;
import https.www_supernotariado_gov_co.schemas.bachue.cr.controldigitalizacion.notificardigitalizacion.v1.TipoSalidaNotificarDigitalizacion;
import https.www_supernotariado_gov_co.services.bachue.cr.controldigitalizacion.v1.SUTCRControlDigitalizacion;


/**
 * Clase de entrada para el servicio expuesto SUT_CN_NotificadorCorrespondencia
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "SUT_CR_ControlDigitalizacionPort", serviceName = "SUT_CR_ControlDigitalizacion", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cr/controldigitalizacion/v1", wsdlLocation = "/wsdls/BS_SUT_CR_ControlDigitalizacion.wsdl", endpointInterface = "https.www_supernotariado_gov_co.services.bachue.cr.controldigitalizacion.v1.SUTCRControlDigitalizacion")
@BindingType("http://www.w3.org/2003/05/soap/bindings/HTTP/")
public class SUT_CR_ControlDigitalizacion_SUT_CR_ControlDigitalizacionPortImpl
    implements SUTCRControlDigitalizacion
{

	/**
	 * Contexto del servicio web
	 */
	@Resource
	private WebServiceContext wsContext;

	/** Manejador de lógica de negocio de procesos */
	@EJB(name = "ProcesoBusiness")
	private ProcesosStatelessLocal procesoControl;

	/** Manejador de lógica de negocio de parámetros */
	@EJB(name = "ParametrosBusiness")
	private ParametrosStatelessLocal parametrosControl;

    /**
     * Invoca al Método principal del servicio, permite avanzar la etapa de un proceso de Digitalización a Aprobación
     * @param entrada Parámetros de entrada del servicio web
     * @return Respuesta del servicio web con el un código de salida y un mensaje
     */
    public TipoSalidaNotificarDigitalizacion notificarDigitalizacion(TipoEntradaNotificarDigitalizacion entrada) {
        //replace with your impl here
    	ControlDigitalizacion servicio = new ControlDigitalizacion();
    	servicio.setProcesoControl(procesoControl);
    	servicio.setParametrosControl(parametrosControl);

    	return servicio.notificarDigitalizacion(entrada, wsContext);
    }

}
